[package]
name = "u2size"
version = "0.1.3"
authors = ["M Farkas-Dyck <strake888@gmail.com>"]
description = "double word integral type"
license = "MIT/Apache-2.0"
repository = "https://github.com/strake/u2size.rs"
